### ISSUE TITLE
TS import fails 

### ISSUE THREAD

**Issue by mikemurray5396** [CharlesNRU/mdm-adminservice#1]
![image](https://user-images.githubusercontent.com/53543351/117355450-7011a080-ae67-11eb-9637-29e802e5671e.png)

View Failure button says "Cannot validate a dependency to Package KL10003E"
Setting Action to Ignore Dependency fails at 33% with "Object reference not set to an instance of an object"

**Comment by CharlesNRU** [comment]
Hi Mike,

What is your site version? I used CB2103 in my lab to export the task sequences. I'm wondering if there's something that is not compatible with older version of Configuration Manager in this export.

**Comment by mikemurray5396** [comment]
Hi,I’m running 2103 as well. 
    	
    	Mike MurraySr. Systems AdministratorCore-Mark International
    
  
 From: Charles ***@***.***>Sent: Friday, May 7, 2021 11:57 AMTo: CharlesNRU/mdm-adminserviceCc: Murray, Mike; AuthorSubject: Re: [CharlesNRU/mdm-adminservice] TS import fails  (#1) 


Hi Mike, What is your site version? I used CB2103 in my lab to export the task sequences. I'm wondering if there's something that is not compatible with older version of Configuration Manager in this export. — You are receiving this because ZjQcmQRYFpfptBannerStart This Message Is From an External Sender This message came from outside your organization. ZjQcmQRYFpfptBannerEndHi Mike,What is your site version? I used CB2103 in my lab to export the task sequences. I'm wondering if there's something that is not compatible with older version of Configuration Manager in this export.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by CharlesNRU** [comment]
I tried importing the task sequences in a different lab and it works fine for me and that one is CB2010...
Are there any details in SmsAdminUI.log that could give us more information in the import failure?

**Comment by mikemurray5396** [comment]
Here is the stack trace from the error when importing:
System.NullReferenceException
Object reference not set to an instance of an object.


Stack Trace:
   at Microsoft.ConfigurationManagement.Migration.ObjectSerialization.Modeling.PrototypeImpl.TryGetPropertyValue(Object instance, String propertyName, Object& value)
   at Microsoft.ConfigurationManagement.Migration.ObjectSerialization.WmiUtility.WriteEmbedded(WmiConnection connection, Prototype type, ManagementBaseObject instance, Object obj)
   at Microsoft.ConfigurationManagement.Migration.ObjectSerialization.WmiConnection.AttachEmbedded(Object embedded)
   at Microsoft.ConfigurationManagement.Migration.ObjectSerialization.WmiUtility.<>c__DisplayClass15_0.<ToWmiObjectValue>b__0(Object v)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.ConfigurationManagement.Migration.ObjectSerialization.WmiUtility.ToWmiObjectValue(WmiConnection connection, Object value, Boolean isArray)
   at Microsoft.ConfigurationManagement.Migration.ObjectSerialization.WmiUtility.ToWmiValue(WmiConnection connection, PropertyData item, Object value)
   at Microsoft.ConfigurationManagement.Migration.ObjectSerialization.WmiUtility.WriteEmbedded(WmiConnection connection, Prototype type, ManagementBaseObject instance, Object obj)
   at Microsoft.ConfigurationManagement.Migration.ObjectSerialization.WmiConnection.AttachEmbedded(Object embedded)
   at Microsoft.ConfigurationManagement.Migration.ObjectSerialization.WmiUtility.ToWmiObjectValue(WmiConnection connection, Object value, Boolean isArray)
   at Microsoft.ConfigurationManagement.Migration.ObjectSerialization.WmiUtility.ToWmiValue(WmiConnection connection, PropertyData item, Object value)
   at Microsoft.ConfigurationManagement.Migration.ObjectSerialization.WmiUtility.WriteInputParameters(WmiConnection connection, ManagementBaseObject parameters, Prototype prototype, Object method)
   at Microsoft.ConfigurationManagement.Migration.ObjectSerialization.WmiConnection.TryExecuteMethod(IObjectContext context, Object method, Object target, IObjectSession cache)
   at Microsoft.ConfigurationManagement.Migration.ObjectSerialization.ObjectLibrary`1.ExecuteMethod(IObjectContext context, IObjectSession cache, Object method, Object target)
   at Microsoft.ConfigurationManagement.Migration.ObjectSerialization.ObjectMethod`1.Execute(IObjectContext context, IObjectSession cache)
   at Microsoft.ConfigurationManagement.Migration.ConfigMgr2012.SMS_TaskSequencePackage.SetSequence(IObjectContext context, SMS_TaskSequencePackage TaskSequencePackage, SMS_TaskSequence TaskSequence, String& SavedTaskSequencePackagePath)
   at Microsoft.ConfigurationManagement.Migration.ConfigMgr2012.SoftwareDistribution.TaskSequenceLibrary.PutInstance(ObjectHandle value, ObjectContext context)
   at Microsoft.ConfigurationManagement.Migration.ObjectSerialization.ObjectContext.SaveChanges(IEnumerable`1 values)
   at Microsoft.ConfigurationManagement.Migration.ObjectSerialization.ImportRequest.Submit()
   at Microsoft.ConfigurationManagement.AdminConsole.MigrationAssistant.FileContentPageControl.PostApply(BackgroundWorker worker, DoWorkEventArgs e)
   at Microsoft.ConfigurationManagement.AdminConsole.SmsWizardPage.PostApply(BackgroundWorker worker, DoWorkEventArgs e)
   at Microsoft.ConfigurationManagement.AdminConsole.SmsWizardForm.PostApply(SmsWizardPage page, BackgroundWorker worker, DoWorkEventArgs e)
   at Microsoft.ConfigurationManagement.AdminConsole.SmsWizardForm.PostApply(BackgroundWorker worker, DoWorkEventArgs e)
   at Microsoft.ConfigurationManagement.AdminConsole.ProgressPage.backgroundWorkerPostApply_DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

-------------------------------
Below is the SMSAdminUI log from when I re-opened the console:
***@***.***D7435A.04E20D40]

Thanks for looking into this!


Mike

**Comment by mikemurray5396** [comment]
Further to my last email – it looks like it’s importing the “Query AdminService for PackageID” TS, but not the other two.

Mike

**Comment by CharlesNRU** [comment]
OK, I can't make anything out of this stack trace :(

Let's try importing the task sequences one by one and see which one(s) are causing issues.
I've attached the separate exports in this message. I've also included a version of the "Query AdminService" TS with the manual MSAL.PS install step disabled so it doesn't warn of a missing package.
Let me know how it goes.
[ApplyBiosPackage.zip](https://github.com/CharlesNRU/mdm-adminservice/files/6444770/ApplyBiosPackage.zip)
[ApplyDriverPackage.zip](https://github.com/CharlesNRU/mdm-adminservice/files/6444771/ApplyDriverPackage.zip)
[QueryAdminService.zip](https://github.com/CharlesNRU/mdm-adminservice/files/6444772/QueryAdminService.zip)
[QueryAdminService_DisabledManualMSALInstall.zip](https://github.com/CharlesNRU/mdm-adminservice/files/6444773/QueryAdminService_DisabledManualMSALInstall.zip)

**Comment by CharlesNRU** [comment]
Hello again,

Can you confirm what is your site version? There are multiple version of CB2103.
Mine is 5.00.9049.1000
Also, I have the task sequence debugger pre-release feature enabled in my lab. If it's not enabled on your site, it might be why it's failing to import.

**Comment by mikemurray5396** [comment]
Hi Charles,

Sorry it took so long to get back to you on this.

Importing the QueryAdminService with the disabled step worked fine. Importing the apply bios and the apply driver TS both failed at the same import error. In each case it fails saying “Cannot validate a dependency to Package KL10003E”. I don’t have the pre-release task sequence debugger enabled, but I can do so and try again if you think that will help.

Mike

**Comment by CharlesNRU** [comment]
OK, so the separate export I did for those 2 still had the step to run the "Query AdminService for PackageID" task sequence enabled which explains the error you get.
Here are both task sequence with the step disabled. If that imports successfully, you will have to re-enable that step and point it to run the task sequence you imported previously.
[ApplyDriverPackage_DisabledQueryAdmin.zip](https://github.com/CharlesNRU/mdm-adminservice/files/6462482/ApplyDriverPackage_DisabledQueryAdmin.zip)
[ApplyBiosPackage_DisabledQueryAdmin.zip](https://github.com/CharlesNRU/mdm-adminservice/files/6462483/ApplyBiosPackage_DisabledQueryAdmin.zip)

Let me know if that works.

**Comment by mikemurray5396** [comment]
Hi Charles,

I still couldn’t import the TS you sent, but I sent a frown to Microsoft. It turns out I may have hit a bug, because they replied that an out-of-band hotfix should be available this week to fix my issue….

Thanks so much for all your time and effort on this!

Mike

**Comment by CharlesNRU** [comment]
OK, let me know if you are able to import the TS after applying the hotfix.

**Comment by CharlesNRU** [comment]
Hi, the fix was released: https://docs.microsoft.com/en-us/mem/configmgr/hotfix/2103/9833643

Install it and let me know if you can import the TS successfully now.

**Comment by mikemurray5396** [comment]
Hi Charles,

I downloaded a fresh copy of the TS from your github repo and imported it successfully. However, there were still warnings about failed dependencies, but when I said to ignore them, the TS imported. I’m currently working through the config.

Thanks again for the blog posts – It’s going to save me a bunch of time & effort!

Mike

**Comment by CharlesNRU** [comment]
Perfect. I'll close this issue then.
